import { Component, OnInit } from '@angular/core';
import { UtilityService } from 'src/app/services/utility.service';

@Component({
  selector: 'app-info-tab',
  templateUrl: './info-tab.component.html',
  styleUrls: ['./info-tab.component.css']
})
export class InfoTabComponent implements OnInit {

  data: any;
  constructor(
    private utilityService: UtilityService
  ) { }

  ngOnInit() {
    this.data = {
        "created_on": "2020-06-18T12:34:06.000Z",
        "modified_on": "2020-06-18T12:46:42.000Z",
        "version": 6,
        "tenant_id": "prasadseeds12",
        "id": 261,
        "user_name": "plantuser",
        "first_name": "Plant",
        "last_name": "User",
        "email": "sreebhavya.a@gmail.com",
        "registered_mobile_no": "9494911451",
        "dept_id": 4,
        "user_devices": [],
        "is_active": true,
        "token": "66972fce-c500-4a86-bf85-889103813111",
        "is_exist": true,
        "last_logged_on": "2020-06-18T12:48:41.000Z",
        "user_token_dto": {
          "version": 0,
          "id": 0,
          "user_id": 261,
          "user_name": "Plant User",
          "access_token": "66972fce-c500-4a86-bf85-889103813111",
          "token_type": "bearer",
          "refresh_token": "f50fbfec-d4a2-457f-8307-04199d1e3b5f",
          "expires_in": 86399,
          "scope": "read write"
        },
        "role_platform": [
          {
            "version": 0,
            "tenant_id": "prasadseeds12",
            "id": 14,
            "code": "RECEIVING-WEBSITE",
            "is_active": true,
            "role_id": 13,
            "platform": {
              "version": 0,
              "tenant_id": "prasadseeds12",
              "id": 2,
              "platform_type": "WEBSITE",
              "platform_description": "website"
            },
            "privileges": [
              {
                "version": 0,
                "tenant_id": "prasadseeds12",
                "id": 30,
                "code": "RECEIVING",
                "description": "Receiving",
                "privilege_type": "Receiving",
                "feature_code": {
                  "created_on": "2019-09-23T15:33:45.000Z",
                  "created_by": 1,
                  "modified_on": "2019-09-23T15:33:45.000Z",
                  "modified_by": 1,
                  "version": 0,
                  "tenant_id": "prasadseeds12",
                  "id": 36,
                  "code": "RECEIVING",
                  "level": "1",
                  "module_name": "plant",
                  "uri": "plant/receiving",
                  "description": "Receiving",
                  "menu_name": "RECEIVING",
                  "parent_id": 0,
                  "type": "ALL",
                  "seq_num": 1,
                  "feature_node_def": {
                    "created_on": "2019-09-23T15:33:45.000Z",
                    "created_by": 1,
                    "modified_on": "2019-09-23T15:33:45.000Z",
                    "modified_by": 1,
                    "version": 0,
                    "tenant_id": "prasadseeds12",
                    "id": 3,
                    "code": "PLANT",
                    "level": "0",
                    "name": "PLANT",
                    "uri": "plant/",
                    "description": "plant",
                    "parent_id": 0,
                    "type": "Home",
                    "seq_num": 1
                  },
                  "child_menu": [
                    {
                      "created_on": "2019-09-23T15:33:45.000Z",
                      "created_by": 1,
                      "modified_on": "2019-09-23T15:33:45.000Z",
                      "modified_by": 1,
                      "version": 0,
                      "tenant_id": "prasadseeds12",
                      "id": 41,
                      "code": "VEHICLE INFORMATION",
                      "level": "1",
                      "module_name": "plant",
                      "uri": "plant/receiving/vehicleinfo",
                      "description": "Vehicle Information",
                      "menu_name": "VEHICLE INFORMATION",
                      "parent_id": 36,
                      "type": "ALL",
                      "seq_num": 1,
                      "feature_node_def": {
                        "created_on": "2019-09-23T15:33:45.000Z",
                        "created_by": 1,
                        "modified_on": "2019-09-23T15:33:45.000Z",
                        "modified_by": 1,
                        "version": 0,
                        "tenant_id": "prasadseeds12",
                        "id": 3,
                        "code": "PLANT",
                        "level": "0",
                        "name": "PLANT",
                        "uri": "plant/",
                        "description": "plant",
                        "parent_id": 0,
                        "type": "Home",
                        "seq_num": 1
                      }
                    },
                    {
                      "created_on": "2019-09-23T15:33:45.000Z",
                      "created_by": 1,
                      "modified_on": "2019-09-23T15:33:45.000Z",
                      "modified_by": 1,
                      "version": 0,
                      "tenant_id": "prasadseeds12",
                      "id": 42,
                      "code": "GROWER INFORMATION",
                      "level": "1",
                      "module_name": "plant",
                      "uri": "plant/receiving/growerInfo",
                      "description": "Grower Information",
                      "menu_name": "GROWER INFORMATION",
                      "parent_id": 36,
                      "type": "ALL",
                      "seq_num": 1,
                      "feature_node_def": {
                        "created_on": "2019-09-23T15:33:45.000Z",
                        "created_by": 1,
                        "modified_on": "2019-09-23T15:33:45.000Z",
                        "modified_by": 1,
                        "version": 0,
                        "tenant_id": "prasadseeds12",
                        "id": 3,
                        "code": "PLANT",
                        "level": "0",
                        "name": "PLANT",
                        "uri": "plant/",
                        "description": "plant",
                        "parent_id": 0,
                        "type": "Home",
                        "seq_num": 1
                      }
                    },
                    {
                      "created_on": "2019-09-23T15:33:45.000Z",
                      "created_by": 1,
                      "modified_on": "2019-09-23T15:33:45.000Z",
                      "modified_by": 1,
                      "version": 0,
                      "tenant_id": "prasadseeds12",
                      "id": 43,
                      "code": "WEIGHING",
                      "level": "1",
                      "module_name": "plant",
                      "uri": "plant/receiving/weighing",
                      "description": "Weighing",
                      "menu_name": "WEIGHING",
                      "parent_id": 36,
                      "type": "ALL",
                      "seq_num": 1,
                      "feature_node_def": {
                        "created_on": "2019-09-23T15:33:45.000Z",
                        "created_by": 1,
                        "modified_on": "2019-09-23T15:33:45.000Z",
                        "modified_by": 1,
                        "version": 0,
                        "tenant_id": "prasadseeds12",
                        "id": 3,
                        "code": "PLANT",
                        "level": "0",
                        "name": "PLANT",
                        "uri": "plant/",
                        "description": "plant",
                        "parent_id": 0,
                        "type": "Home",
                        "seq_num": 1
                      }
                    },
                    {
                      "created_on": "2019-09-23T15:33:45.000Z",
                      "created_by": 1,
                      "modified_on": "2019-09-23T15:33:45.000Z",
                      "modified_by": 1,
                      "version": 0,
                      "tenant_id": "prasadseeds12",
                      "id": 44,
                      "code": "SAMPLING",
                      "level": "1",
                      "module_name": "plant",
                      "uri": "plant/receiving/sampling",
                      "description": "Sampling",
                      "menu_name": "SAMPLING",
                      "parent_id": 36,
                      "type": "ALL",
                      "seq_num": 1,
                      "feature_node_def": {
                        "created_on": "2019-09-23T15:33:45.000Z",
                        "created_by": 1,
                        "modified_on": "2019-09-23T15:33:45.000Z",
                        "modified_by": 1,
                        "version": 0,
                        "tenant_id": "prasadseeds12",
                        "id": 3,
                        "code": "PLANT",
                        "level": "0",
                        "name": "PLANT",
                        "uri": "plant/",
                        "description": "plant",
                        "parent_id": 0,
                        "type": "Home",
                        "seq_num": 1
                      }
                    },
                    {
                      "created_on": "2019-09-23T15:33:45.000Z",
                      "created_by": 1,
                      "modified_on": "2019-09-23T15:33:45.000Z",
                      "modified_by": 1,
                      "version": 0,
                      "tenant_id": "prasadseeds12",
                      "id": 45,
                      "code": "BIN ALLOCATION",
                      "level": "1",
                      "module_name": "plant",
                      "uri": "plant/receiving/binalloc",
                      "description": "Bin Allocation",
                      "menu_name": "BIN ALLOCATION",
                      "parent_id": 36,
                      "type": "ALL",
                      "seq_num": 1,
                      "feature_node_def": {
                        "created_on": "2019-09-23T15:33:45.000Z",
                        "created_by": 1,
                        "modified_on": "2019-09-23T15:33:45.000Z",
                        "modified_by": 1,
                        "version": 0,
                        "tenant_id": "prasadseeds12",
                        "id": 3,
                        "code": "PLANT",
                        "level": "0",
                        "name": "PLANT",
                        "uri": "plant/",
                        "description": "plant",
                        "parent_id": 0,
                        "type": "Home",
                        "seq_num": 1
                      }
                    }
                  ]
                }
              }
            ]
          },
          {
            "version": 0,
            "tenant_id": "prasadseeds12",
            "id": 14,
            "code": "RECEIVING-WEBSITE",
            "is_active": true,
            "role_id": 13,
            "platform": {
              "version": 0,
              "tenant_id": "prasadseeds12",
              "id": 2,
              "platform_type": "WEBSITE",
              "platform_description": "website"
            },
            "privileges": [
              {
                "version": 0,
                "tenant_id": "prasadseeds12",
                "id": 30,
                "code": "RECEIVING",
                "description": "Receiving",
                "privilege_type": "Receiving",
                "feature_code": {
                  "created_on": "2019-09-23T15:33:45.000Z",
                  "created_by": 1,
                  "modified_on": "2019-09-23T15:33:45.000Z",
                  "modified_by": 1,
                  "version": 0,
                  "tenant_id": "prasadseeds12",
                  "id": 36,
                  "code": "RECEIVING",
                  "level": "1",
                  "module_name": "plant",
                  "uri": "plant/receiving",
                  "description": "Receiving",
                  "menu_name": "RECEIVING",
                  "parent_id": 0,
                  "type": "ALL",
                  "seq_num": 1,
                  "feature_node_def": {
                    "created_on": "2019-09-23T15:33:45.000Z",
                    "created_by": 1,
                    "modified_on": "2019-09-23T15:33:45.000Z",
                    "modified_by": 1,
                    "version": 0,
                    "tenant_id": "prasadseeds12",
                    "id": 3,
                    "code": "PLANT",
                    "level": "0",
                    "name": "PLANT",
                    "uri": "plant/",
                    "description": "plant",
                    "parent_id": 0,
                    "type": "Home",
                    "seq_num": 1
                  },
                  "child_menu": [
                    {
                      "created_on": "2019-09-23T15:33:45.000Z",
                      "created_by": 1,
                      "modified_on": "2019-09-23T15:33:45.000Z",
                      "modified_by": 1,
                      "version": 0,
                      "tenant_id": "prasadseeds12",
                      "id": 41,
                      "code": "VEHICLE INFORMATION",
                      "level": "1",
                      "module_name": "plant",
                      "uri": "plant/receiving/vehicleinfo",
                      "description": "Vehicle Information",
                      "menu_name": "VEHICLE INFORMATION",
                      "parent_id": 36,
                      "type": "ALL",
                      "seq_num": 1,
                      "feature_node_def": {
                        "created_on": "2019-09-23T15:33:45.000Z",
                        "created_by": 1,
                        "modified_on": "2019-09-23T15:33:45.000Z",
                        "modified_by": 1,
                        "version": 0,
                        "tenant_id": "prasadseeds12",
                        "id": 3,
                        "code": "PLANT",
                        "level": "0",
                        "name": "PLANT",
                        "uri": "plant/",
                        "description": "plant",
                        "parent_id": 0,
                        "type": "Home",
                        "seq_num": 1
                      }
                    },
                    {
                      "created_on": "2019-09-23T15:33:45.000Z",
                      "created_by": 1,
                      "modified_on": "2019-09-23T15:33:45.000Z",
                      "modified_by": 1,
                      "version": 0,
                      "tenant_id": "prasadseeds12",
                      "id": 42,
                      "code": "GROWER INFORMATION",
                      "level": "1",
                      "module_name": "plant",
                      "uri": "plant/receiving/growerInfo",
                      "description": "Grower Information",
                      "menu_name": "GROWER INFORMATION",
                      "parent_id": 36,
                      "type": "ALL",
                      "seq_num": 1,
                      "feature_node_def": {
                        "created_on": "2019-09-23T15:33:45.000Z",
                        "created_by": 1,
                        "modified_on": "2019-09-23T15:33:45.000Z",
                        "modified_by": 1,
                        "version": 0,
                        "tenant_id": "prasadseeds12",
                        "id": 3,
                        "code": "PLANT",
                        "level": "0",
                        "name": "PLANT",
                        "uri": "plant/",
                        "description": "plant",
                        "parent_id": 0,
                        "type": "Home",
                        "seq_num": 1
                      }
                    },
                    {
                      "created_on": "2019-09-23T15:33:45.000Z",
                      "created_by": 1,
                      "modified_on": "2019-09-23T15:33:45.000Z",
                      "modified_by": 1,
                      "version": 0,
                      "tenant_id": "prasadseeds12",
                      "id": 43,
                      "code": "WEIGHING",
                      "level": "1",
                      "module_name": "plant",
                      "uri": "plant/receiving/weighing",
                      "description": "Weighing",
                      "menu_name": "WEIGHING",
                      "parent_id": 36,
                      "type": "ALL",
                      "seq_num": 1,
                      "feature_node_def": {
                        "created_on": "2019-09-23T15:33:45.000Z",
                        "created_by": 1,
                        "modified_on": "2019-09-23T15:33:45.000Z",
                        "modified_by": 1,
                        "version": 0,
                        "tenant_id": "prasadseeds12",
                        "id": 3,
                        "code": "PLANT",
                        "level": "0",
                        "name": "PLANT",
                        "uri": "plant/",
                        "description": "plant",
                        "parent_id": 0,
                        "type": "Home",
                        "seq_num": 1
                      }
                    },
                    {
                      "created_on": "2019-09-23T15:33:45.000Z",
                      "created_by": 1,
                      "modified_on": "2019-09-23T15:33:45.000Z",
                      "modified_by": 1,
                      "version": 0,
                      "tenant_id": "prasadseeds12",
                      "id": 44,
                      "code": "SAMPLING",
                      "level": "1",
                      "module_name": "plant",
                      "uri": "plant/receiving/sampling",
                      "description": "Sampling",
                      "menu_name": "SAMPLING",
                      "parent_id": 36,
                      "type": "ALL",
                      "seq_num": 1,
                      "feature_node_def": {
                        "created_on": "2019-09-23T15:33:45.000Z",
                        "created_by": 1,
                        "modified_on": "2019-09-23T15:33:45.000Z",
                        "modified_by": 1,
                        "version": 0,
                        "tenant_id": "prasadseeds12",
                        "id": 3,
                        "code": "PLANT",
                        "level": "0",
                        "name": "PLANT",
                        "uri": "plant/",
                        "description": "plant",
                        "parent_id": 0,
                        "type": "Home",
                        "seq_num": 1
                      }
                    },
                    {
                      "created_on": "2019-09-23T15:33:45.000Z",
                      "created_by": 1,
                      "modified_on": "2019-09-23T15:33:45.000Z",
                      "modified_by": 1,
                      "version": 0,
                      "tenant_id": "prasadseeds12",
                      "id": 45,
                      "code": "BIN ALLOCATION",
                      "level": "1",
                      "module_name": "plant",
                      "uri": "plant/receiving/binalloc",
                      "description": "Bin Allocation",
                      "menu_name": "BIN ALLOCATION",
                      "parent_id": 36,
                      "type": "ALL",
                      "seq_num": 1,
                      "feature_node_def": {
                        "created_on": "2019-09-23T15:33:45.000Z",
                        "created_by": 1,
                        "modified_on": "2019-09-23T15:33:45.000Z",
                        "modified_by": 1,
                        "version": 0,
                        "tenant_id": "prasadseeds12",
                        "id": 3,
                        "code": "PLANT",
                        "level": "0",
                        "name": "PLANT",
                        "uri": "plant/",
                        "description": "plant",
                        "parent_id": 0,
                        "type": "Home",
                        "seq_num": 1
                      }
                    }
                  ]
                }
              }
            ]
          }
        ]
    }
    this.utilityService.getPrivilages(this.data['role_platform']);
  }

}
